<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite hostname="Poonam-PC" name="com.Test.TestGmailLogin.TestGmailLogin" tests="5" failures="0" timestamp="23 Feb 2015 13:44:44 GMT" time="9.074" errors="1">
  <testcase name="enterNullInputs" time="0.726" classname="com.Test.TestGmailLogin.TestGmailLogin">
    <error type="java.lang.AssertionError" message="expected [Enter your email address] but found [Enter your email address.]">
      <![CDATA[java.lang.AssertionError: expected [Enter your email address] but found [Enter your email address.]
	at org.testng.Assert.fail(Assert.java:94)
	at org.testng.Assert.failNotEquals(Assert.java:494)
	at org.testng.Assert.assertEquals(Assert.java:123)
	at org.testng.Assert.assertEquals(Assert.java:176)
	at org.testng.Assert.assertEquals(Assert.java:186)
	at com.Test.TestGmailLogin.TestGmailLogin.enterNullInputs(TestGmailLogin.java:46)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:84)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:714)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:901)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1231)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:127)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:111)
	at org.testng.TestRunner.privateRun(TestRunner.java:767)
	at org.testng.TestRunner.run(TestRunner.java:617)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:334)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:329)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:291)
	at org.testng.SuiteRunner.run(SuiteRunner.java:240)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1224)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1149)
	at org.testng.TestNG.run(TestNG.java:1057)
	at org.testng.remote.RemoteTestNG.run(RemoteTestNG.java:111)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:204)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:175)
]]>
    </error>
  </testcase> <!-- enterNullInputs -->
  <testcase name="enterCorrectUserNamePassword" time="5.072" classname="com.Test.TestGmailLogin.TestGmailLogin"/>
  <testcase name="enterIncorrectUserNamePassword" time="1.261" classname="com.Test.TestGmailLogin.TestGmailLogin"/>
  <testcase name="enterPasswordOnly" time="0.893" classname="com.Test.TestGmailLogin.TestGmailLogin"/>
  <testcase name="enterUserNameOnly" time="1.122" classname="com.Test.TestGmailLogin.TestGmailLogin"/>
</testsuite> <!-- com.Test.TestGmailLogin.TestGmailLogin -->
